config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 20, maximum: 300 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def new
    @article=Article.new
  end

  def index
    @articles=Article.all
  end


  def edit

  end

  def destroy

    @article.destroy
    flash[:notice]="Article was successfully deleted"
    redirect_to articles_path

  end




  def save
  end

  def show

  end

  def create
    @article=Article.new(article_params)
    if @article.save
      flash[:notice]="Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end


  def update

    if @article.update(article_params)
      flash[:notice]="Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  private

    def set_article
      @article=Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end


  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end



end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented your article from being saved</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li> <%= msg %> </li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to "Back to Article Listing", articles_path %> </p>

app/views/articles/edit.html.erb
<h1>Edit Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing of All Articles</h1>
<%= link_to "Create New Article", new_article_path %><br><br>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>

    <td><%= article.created_at %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Add New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<H1> The new article has been saved </h1>

<p>Title: <%= @article.title %> </p>
<p>Description: <%= @article.description %> </p>
<p><%= link_to "Back to Article Listing", articles_path %> &nbsp; &nbsp; <%= link_to "Edit this Article", edit_article_path(@article) %>

app/views/layouts/_messages.html.erb
<% flash.each do |msg| %>
  <ul>
    <li> <%= msg %> </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |msg| %>
    <ul>
      <li> <% msg %> </li>
    </ul>
  <% end %>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<H1>About Us</H1>

app/views/pages/home.html.erb
<h1>This is the Home Page of My Blog</h1>

<%= link_to 'Alpha Blog', articles_path %> | <%= link_to 'About', pages_about_path %>